runtime: php72
#api_version: 1
#threadsafe: true

handlers:

- url: /css
  secure: always
  static_dir: css
  
- url: /scripts
  secure: always
  static_dir: scripts
  
- url: /fonts
  static_dir: fonts
  
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
