--
-- Database: `pokedex`
--
CREATE DATABASE IF NOT EXISTS `pokedex` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `pokedex`;

-- --------------------------------------------------------

--
-- Table structure for table `Learnsets`
--
-- Creation: Jun 14, 2017 at 06:02 PM
--

CREATE TABLE `Learnsets` (
  `Species` varchar(15) DEFAULT NULL,
  `Move` varchar(30) DEFAULT NULL,
  `Gen` set('I','II','III','IV','V','VI','VII') DEFAULT 'VII'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- RELATIONSHIPS FOR TABLE `Learnsets`:
--   `Move`
--       `Moves` -> `Name`
--   `Species`
--       `Masterlist` -> `Species`
--

--
-- Dumping data for table `Learnsets`
--

INSERT INTO `Learnsets` (`Species`, `Move`, `Gen`) VALUES
('Bulbasaur', 'Growl', 'VII'),
('Bulbasaur', 'Tackle', 'VII');

-- --------------------------------------------------------

--
-- Table structure for table `Masterlist`
--
-- Creation: Oct 08, 2017 at 07:25 PM
--

CREATE TABLE `Masterlist` (
  `ID` int(5) NOT NULL,
  `Species` varchar(15) DEFAULT NULL,
  `Nickname` varchar(15) DEFAULT NULL,
  `Gender` tinyint(1) DEFAULT '0' COMMENT '0 = male; 1 = female',
  `Caught` tinyint(1) DEFAULT '0' COMMENT '0 = no; 1 = yes',
  `Shiny` tinyint(1) DEFAULT '0' COMMENT '0 = no; 1 = yes',
  `Region` varchar(10) DEFAULT NULL,
  `Held_Item` varchar(15) DEFAULT NULL,
  `Nature` varchar(15) DEFAULT NULL,
  `Move1` varchar(15) DEFAULT NULL,
  `Move2` varchar(15) DEFAULT NULL,
  `Move3` varchar(15) DEFAULT NULL,
  `Move4` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- RELATIONSHIPS FOR TABLE `Masterlist`:
--   `Move1`
--       `Learnsets` -> `Move`
--   `Move2`
--       `Learnsets` -> `Move`
--   `Move3`
--       `Learnsets` -> `Move`
--   `Move4`
--       `Learnsets` -> `Move`
--   `Nature`
--       `Natures` -> `Name`
--   `Region`
--       `Regions` -> `Name`
--

--
-- Dumping data for table `Masterlist`
--

INSERT INTO `Masterlist` (`ID`, `Species`, `Nickname`, `Gender`, `Caught`, `Shiny`, `Region`, `Held_Item`, `Nature`, `Move1`, `Move2`, `Move3`, `Move4`) VALUES
(1, 'Bulbasaur', 'Dane', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Ivysaur', 'Sou', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(3, 'Venusaur', 'Bana', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(4, 'Charmander', 'Dai', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(5, 'Charmeleon', 'Aka', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'Charizard', 'Kuroshi', 0, 0, 0, 'Kanto', NULL, 'Modest', NULL, NULL, NULL, NULL),
(7, 'Squirtle', 'Mizu', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'Wartortle', 'Chai', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(9, 'Blastoise', 'Ao', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(10, 'Caterpie', 'Ilio', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'Metapod', 'Lucas', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'Butterfree', 'Oria', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'Weedle', 'Roth', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(14, 'Kakuna', 'Lang', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'Beedrill', 'Oscar', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'Pidgey', 'Dar', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'Pidgeotto', 'Estra', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'Pidgeot', 'Thane', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'Rattata', 'Nora', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'Raticate', 'Rex', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'Spearow', 'Falco', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(22, 'Fearow', 'Inga', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'Ekans', 'Talus', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'Arbok', 'Naj', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'Pikachu', 'Rau', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(26, 'Raichu', 'Pella', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'Sandshrew', 'Sable', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'Sandslash', 'Rin', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'Nidoran', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'Nidorina', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'Nidoqueen', 'Zena', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'Nidoran', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'Nidorino', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'Nidoking', 'Kai', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'Clefairy', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(36, 'Clefable', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(37, 'Vulpix', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(38, 'Ninetales', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(39, 'Jigglypuff', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(40, 'Wigglytuff', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(41, 'Zubat', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'Golbat', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'Oddish', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'Gloom', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(45, 'Vileplume', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'Paras', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(47, 'Parasect', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'Venonat', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'Venomoth', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(50, 'Diglett', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(51, 'Dugtrio', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'Meowth', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(53, 'Persian', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'Psyduck', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(55, 'Golduck', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(56, 'Mankey', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'Primeape', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(58, 'Growlithe', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'Arcanine', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(60, 'Poliwag', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(61, 'Poliwhirl', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(62, 'Poliwrath', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(63, 'Abra', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(64, 'Kadabra', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(65, 'Alakazam', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(66, 'Machop', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(67, 'Machoke', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(68, 'Machamp', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(69, 'Bellsprout', 'Datsu', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(70, 'Weepinbell', 'Kazura', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'Victreebel', 'Nepenthe', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(72, 'Tentacool', 'Pan', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(73, 'Tentacruel', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(74, 'Geodude', 'Maline', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(75, 'Graveler', 'Goron', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(76, 'Golem', 'Iona', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(77, 'Ponyta', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(78, 'Rapidash', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(79, 'Slowpoke', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(80, 'Slowbro', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(81, 'Magnemite', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(82, 'Magneton', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(83, 'Farfetch\'d', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(84, 'Doduo', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(85, 'Dodrio', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(86, 'Seel', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(87, 'Dewgong', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(88, 'Grimer', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(89, 'Muk', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(90, 'Shellder', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(91, 'Cloyster', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(92, 'Gastly', 'Tira', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(93, 'Haunter', 'Puck', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(94, 'Gengar', 'Roshi', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(95, 'Onix', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(96, 'Drowzee', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(97, 'Hypno', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(98, 'Krabby', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(99, 'Kingler', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(100, 'Voltorb', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(101, 'Electrode', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(102, 'Exeggcute', 'Tama', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(103, 'Exeggutor', 'Menju', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(104, 'Cubone', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(105, 'Marowak', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(106, 'Hitmonlee', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(107, 'Hitmonchan', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(108, 'Lickitung', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(109, 'Koffing', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(110, 'Weezing', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(111, 'Rhyhorn', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(112, 'Rhydon', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(113, 'Chansey', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(114, 'Tangela', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(115, 'Kangaskhan', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(116, 'Horsea', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(117, 'Seadra', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(118, 'Goldeen', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(119, 'Seaking', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(120, 'Staryu', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(121, 'Starmie', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(122, 'Mr. Mime', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(123, 'Scyther', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(124, 'Jynx', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(125, 'Electabuzz', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(126, 'Magmar', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(127, 'Pinsir', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(128, 'Tauros', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(129, 'Magikarp', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(130, 'Gyarados', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(131, 'Lapras', 'Serendipity', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(132, 'Ditto', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(133, 'Eevee', 'Qianru', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(134, 'Vaporeon', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(135, 'Jolteon', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(136, 'Flareon', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(137, 'Porygon', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(138, 'Omanyte', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(139, 'Omastar', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(140, 'Kabuto', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(141, 'Kabutops', 'Rictus', 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(142, 'Aerodactyl', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(143, 'Snorlax', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(144, 'Articuno', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(145, 'Zapdos', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(146, 'Moltres', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(147, 'Dratini', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(148, 'Dragonair', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(149, 'Dragonite', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(150, 'Mewtwo', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(151, 'Mew', NULL, 0, 0, 0, 'Kanto', NULL, NULL, NULL, NULL, NULL, NULL),
(152, 'Chikorita', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(153, 'Bayleef', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(154, 'Meganium', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(155, 'Cyndaquil', 'Hina', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(156, 'Quilava', 'Mara', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(157, 'Typhlosion', 'Kanjou', 0, 0, 0, 'Johto', NULL, 'Modest', 'Flamethrower', 'Focus Blast', 'Solar Beam', 'Sunny Day'),
(158, 'Totodile', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(159, 'Croconaw', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(160, 'Feraligatr', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(161, 'Sentret', 'Beri', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(162, 'Furret', 'Linnaeus', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(163, 'Hoothoot', 'Pascal', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(164, 'Noctowl', 'Sinclair', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(165, 'Ledyba', 'Inell', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(166, 'Ledian', 'Silas', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(167, 'Spinarak', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(168, 'Ariados', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(169, 'Crobat', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(170, 'Chinchou', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(171, 'Lanturn', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(172, 'Pichu', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(173, 'Cleffa', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(174, 'Igglybuff', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(175, 'Togepi', 'Piyo', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(176, 'Togetic', 'Fay', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(177, 'Natu', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(178, 'Xatu', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(179, 'Mareep', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(180, 'Flaaffy', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(181, 'Ampharos', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(182, 'Bellossom', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(183, 'Marill', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(184, 'Azumarill', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(185, 'Sudowoodo', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(186, 'Politoed', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(187, 'Hoppip', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(188, 'Skiploom', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(189, 'Jumpluff', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(190, 'Aipom', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(191, 'Sunkern', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(192, 'Sunflora', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(193, 'Yanma', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(194, 'Wooper', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(195, 'Quagsire', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(196, 'Espeon', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(197, 'Umbreon', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(198, 'Murkrow', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(199, 'Slowking', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(200, 'Misdreavus', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(201, 'Unown', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(202, 'Wobbuffet', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(203, 'Girafarig', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(204, 'Pineco', 'Duval', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(205, 'Forretress', 'Castan', 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(206, 'Dunsparce', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(207, 'Gligar', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(208, 'Steelix', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(209, 'Snubbull', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(210, 'Granbull', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(211, 'Qwilfish', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(212, 'Scizor', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(213, 'Shuckle', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(214, 'Heracross', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(215, 'Sneasel', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(216, 'Teddiursa', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(217, 'Ursaring', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(218, 'Slugma', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(219, 'Magcargo', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(220, 'Swinub', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(221, 'Piloswine', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(222, 'Corsola', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(223, 'Remoraid', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(224, 'Octillery', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(225, 'Delibird', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(226, 'Mantine', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(227, 'Skarmory', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(228, 'Houndour', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(229, 'Houndoom', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(230, 'Kingdra', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(231, 'Phanpy', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(232, 'Donphan', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(233, 'Porygon2', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(234, 'Stantler', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(235, 'Smeargle', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(236, 'Tyrogue', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(237, 'Hitmontop', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(238, 'Smoochum', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(239, 'Elekid', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(240, 'Magby', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(241, 'Miltank', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(242, 'Blissey', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(243, 'Raikou', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(244, 'Entei', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(245, 'Suicune', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(246, 'Larvitar', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(247, 'Pupitar', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(248, 'Tyranitar', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(249, 'Lugia', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(250, 'Ho-Oh', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(251, 'Celebi', NULL, 0, 0, 0, 'Johto', NULL, NULL, NULL, NULL, NULL, NULL),
(252, 'Treecko', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(253, 'Grovyle', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(254, 'Sceptile', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(255, 'Torchic', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(256, 'Combusken', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(257, 'Blaziken', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(258, 'Mudkip', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(259, 'Marshtomp', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(260, 'Swampert', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(261, 'Poochyena', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(262, 'Mightyena', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(263, 'Zigzagoon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(264, 'Linoone', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(265, 'Wurmple', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(266, 'Silcoon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(267, 'Beautifly', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(268, 'Cascoon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(269, 'Dustox', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(270, 'Lotad', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(271, 'Lombre', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(272, 'Ludicolo', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(273, 'Seedot', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(274, 'Nuzleaf', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(275, 'Shiftry', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(276, 'Taillow', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(277, 'Swellow', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(278, 'Wingull', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(279, 'Pelipper', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(280, 'Ralts', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(281, 'Kirlia', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(282, 'Gardevoir', 'Khaleesi', 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(283, 'Surskit', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(284, 'Masquerain', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(285, 'Shroomish', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(286, 'Breloom', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(287, 'Slakoth', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(288, 'Vigoroth', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(289, 'Slaking', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(290, 'Nincada', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(291, 'Ninjask', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(292, 'Shedinja', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(293, 'Whismur', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(294, 'Loudred', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(295, 'Exploud', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(296, 'Makuhita', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(297, 'Hariyama', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(298, 'Azurill', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(299, 'Nosepass', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(300, 'Skitty', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(301, 'Delcatty', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(302, 'Sableye', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(303, 'Mawile', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(304, 'Aron', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(305, 'Lairon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(306, 'Aggron', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(307, 'Meditite', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(308, 'Medicham', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(309, 'Electrike', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(310, 'Manectric', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(311, 'Plusle', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(312, 'Minun', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(313, 'Volbeat', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(314, 'Illumise', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(315, 'Roselia', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(316, 'Gulpin', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(317, 'Swalot', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(318, 'Carvanha', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(319, 'Sharpedo', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(320, 'Wailmer', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(321, 'Wailord', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(322, 'Numel', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(323, 'Camerupt', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(324, 'Torkoal', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(325, 'Spoink', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(326, 'Grumpig', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(327, 'Spinda', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(328, 'Trapinch', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(329, 'Vibrava', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(330, 'Flygon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(331, 'Cacnea', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(332, 'Cacturne', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(333, 'Swablu', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(334, 'Altaria', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(335, 'Zangoose', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(336, 'Seviper', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(337, 'Lunatone', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(338, 'Solrock', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(339, 'Barboach', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(340, 'Whiscash', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(341, 'Corphish', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(342, 'Crawdaunt', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(343, 'Baltoy', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(344, 'Claydol', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(345, 'Lileep', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(346, 'Cradily', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(347, 'Anorith', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(348, 'Armaldo', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(349, 'Feebas', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(350, 'Milotic', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(351, 'Castform', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(352, 'Kecleon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(353, 'Shuppet', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(354, 'Banette', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(355, 'Duskull', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(356, 'Dusclops', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(357, 'Tropius', 'Siana', 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(358, 'Chimecho', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(359, 'Absol', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(360, 'Wynaut', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(361, 'Snorunt', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(362, 'Glalie', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(363, 'Spheal', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(364, 'Sealeo', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(365, 'Walrein', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(366, 'Clamperl', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(367, 'Huntail', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(368, 'Gorebyss', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(369, 'Relicanth', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(370, 'Luvdisc', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(371, 'Bagon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(372, 'Shelgon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(373, 'Salamence', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(374, 'Beldum', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(375, 'Metang', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(376, 'Metagross', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(377, 'Regirock', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(378, 'Regice', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(379, 'Registeel', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(380, 'Latias', 'Gloria', 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(381, 'Latios', 'Aerius', 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(382, 'Kyogre', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(383, 'Groudon', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(384, 'Rayquaza', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(385, 'Jirachi', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(386, 'Deoxys', NULL, 0, 0, 0, 'Hoenn', NULL, NULL, NULL, NULL, NULL, NULL),
(387, 'Turtwig', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(388, 'Grotle', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(389, 'Torterra', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(390, 'Chimchar', 'Rousey', 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(391, 'Monferno', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(392, 'Infernape', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(393, 'Piplup', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(394, 'Prinplup', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(395, 'Empoleon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(396, 'Starly', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(397, 'Staravia', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(398, 'Staraptor', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(399, 'Bidoof', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(400, 'Bibarel', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(401, 'Kricketot', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(402, 'Kricketune', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(403, 'Shinx', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(404, 'Luxio', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(405, 'Luxray', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(406, 'Budew', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(407, 'Roserade', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(408, 'Cranidos', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(409, 'Rampardos', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(410, 'Shieldon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(411, 'Bastiodon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(412, 'Burmy', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(413, 'Wormadam', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(414, 'Mothim', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(415, 'Combee', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(416, 'Vespiquen', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(417, 'Pachirisu', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(418, 'Buizel', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(419, 'Floatzel', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(420, 'Cherubi', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(421, 'Cherrim', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(422, 'Shellos', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(423, 'Gastrodon', 'Charon', 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(424, 'Ambipom', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(425, 'Drifloon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(426, 'Drifblim', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(427, 'Buneary', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(428, 'Lopunny', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(429, 'Mismagius', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(430, 'Honchkrow', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(431, 'Glameow', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(432, 'Purugly', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(433, 'Chingling', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(434, 'Stunky', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(435, 'Skuntank', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(436, 'Bronzor', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(437, 'Bronzong', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(438, 'Bonsly', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(439, 'Mime-Jr', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(440, 'Happiny', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(441, 'Chatot', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(442, 'Spiritomb', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(443, 'Gible', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(444, 'Gabite', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(445, 'Garchomp', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(446, 'Munchlax', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(447, 'Riolu', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(448, 'Lucario', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(449, 'Hippopotas', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(450, 'Hippowdon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(451, 'Skorupi', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(452, 'Drapion', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(453, 'Croagunk', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(454, 'Toxicroak', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(455, 'Carnivine', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(456, 'Finneon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(457, 'Lumineon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(458, 'Mantyke', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(459, 'Snover', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(460, 'Abomasnow', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(461, 'Weavile', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(462, 'Magnezone', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(463, 'Lickilicky', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(464, 'Rhyperior', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(465, 'Tangrowth', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(466, 'Electivire', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(467, 'Magmortar', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(468, 'Togekiss', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(469, 'Yanmega', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(470, 'Leafeon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(471, 'Glaceon', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(472, 'Gliscor', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(473, 'Mamoswine', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(474, 'Porygon-Z', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(475, 'Gallade', 'Khal', 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(476, 'Probopass', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(477, 'Dusknoir', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(478, 'Froslass', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(479, 'Rotom', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(480, 'Uxie', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(481, 'Mesprit', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(482, 'Azelf', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(483, 'Dialga', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(484, 'Palkia', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(485, 'Heatran', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(486, 'Regigigas', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(487, 'Giratina', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(488, 'Cresselia', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(489, 'Phione', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(490, 'Manaphy', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(491, 'Darkrai', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(492, 'Shaymin', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(493, 'Arceus', NULL, 0, 0, 0, 'Sinnoh', NULL, NULL, NULL, NULL, NULL, NULL),
(494, 'Victini', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(495, 'Snivy', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(496, 'Servine', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(497, 'Serperior', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(498, 'Tepig', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(499, 'Pignite', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(500, 'Emboar', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(501, 'Oshawott', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(502, 'Dewott', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(503, 'Samurott', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(504, 'Patrat', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(505, 'Watchog', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(506, 'Lillipup', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(507, 'Herdier', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(508, 'Stoutland', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(509, 'Purrloin', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(510, 'Liepard', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(511, 'Pansage', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(512, 'Simisage', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(513, 'Pansear', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(514, 'Simisear', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(515, 'Panpour', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(516, 'Simipour', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(517, 'Munna', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(518, 'Musharna', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(519, 'Pidove', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(520, 'Tranquill', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(521, 'Unfezant', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(522, 'Blitzle', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(523, 'Zebstrika', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(524, 'Roggenrola', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(525, 'Boldore', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(526, 'Gigalith', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(527, 'Woobat', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(528, 'Swoobat', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(529, 'Drilbur', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(530, 'Excadrill', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(531, 'Audino', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(532, 'Timburr', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(533, 'Gurdurr', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(534, 'Conkeldurr', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(535, 'Tympole', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(536, 'Palpitoad', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(537, 'Seismitoad', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(538, 'Throh', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(539, 'Sawk', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(540, 'Sewaddle', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(541, 'Swadloon', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(542, 'Leavanny', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(543, 'Venipede', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(544, 'Whirlipede', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(545, 'Scolipede', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(546, 'Cottonee', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(547, 'Whimsicott', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(548, 'Petilil', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(549, 'Lilligant', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(550, 'Basculin', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(551, 'Sandile', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(552, 'Krokorok', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(553, 'Krookodile', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(554, 'Darumaka', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(555, 'Darmanitan', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(556, 'Maractus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(557, 'Dwebble', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(558, 'Crustle', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(559, 'Scraggy', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(560, 'Scrafty', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(561, 'Sigilyph', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(562, 'Yamask', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(563, 'Cofagrigus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(564, 'Tirtouga', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(565, 'Carracosta', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(566, 'Archen', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(567, 'Archeops', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(568, 'Trubbish', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(569, 'Garbodor', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(570, 'Zorua', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(571, 'Zoroark', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(572, 'Minccino', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(573, 'Cinccino', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(574, 'Gothita', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(575, 'Gothorita', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(576, 'Gothitelle', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(577, 'Solosis', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(578, 'Duosion', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(579, 'Reuniclus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(580, 'Ducklett', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(581, 'Swanna', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(582, 'Vanillite', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(583, 'Vanillish', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(584, 'Vanilluxe', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(585, 'Deerling', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(586, 'Sawsbuck', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(587, 'Emolga', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(588, 'Karrablast', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(589, 'Escavalier', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(590, 'Foongus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(591, 'Amoonguss', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(592, 'Frillish', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(593, 'Jellicent', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(594, 'Alomomola', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(595, 'Joltik', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(596, 'Galvantula', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(597, 'Ferroseed', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(598, 'Ferrothorn', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(599, 'Klink', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(600, 'Klang', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(601, 'Klinklang', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(602, 'Tynamo', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(603, 'Eelektrik', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(604, 'Eelektross', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(605, 'Elgyem', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(606, 'Beheeyem', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(607, 'Litwick', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(608, 'Lampent', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(609, 'Chandelure', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(610, 'Axew', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(611, 'Fraxure', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(612, 'Haxorus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(613, 'Cubchoo', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(614, 'Beartic', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(615, 'Cryogonal', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(616, 'Shelmet', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(617, 'Accelgor', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(618, 'Stunfisk', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(619, 'Mienfoo', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(620, 'Mienshao', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(621, 'Druddigon', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(622, 'Golett', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(623, 'Golurk', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(624, 'Pawniard', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(625, 'Bisharp', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(626, 'Bouffalant', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(627, 'Rufflet', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(628, 'Braviary', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(629, 'Vullaby', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(630, 'Mandibuzz', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(631, 'Heatmor', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(632, 'Durant', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(633, 'Deino', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(634, 'Zweilous', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(635, 'Hydreigon', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(636, 'Larvesta', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(637, 'Volcarona', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(638, 'Cobalion', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(639, 'Terrakion', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(640, 'Virizion', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(641, 'Tornadus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(642, 'Thundurus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(643, 'Reshiram', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(644, 'Zekrom', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(645, 'Landorus', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(646, 'Kyurem', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(647, 'Keldeo', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(648, 'Meloetta', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL),
(649, 'Genesect', NULL, 0, 0, 0, 'Unova', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `Masterlist` (`ID`, `Species`, `Nickname`, `Gender`, `Caught`, `Shiny`, `Region`, `Held_Item`, `Nature`, `Move1`, `Move2`, `Move3`, `Move4`) VALUES
(650, 'Chespin', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(651, 'Quilladin', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(652, 'Chesnaught', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(653, 'Fennekin', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(654, 'Braixen', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(655, 'Delphox', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(656, 'Froakie', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(657, 'Frogadier', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(658, 'Greninja', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(659, 'Bunnelby', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(660, 'Diggersby', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(661, 'Fletchling', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(662, 'Fletchinder', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(663, 'Talonflame', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(664, 'Scatterbug', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(665, 'Spewpa', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(666, 'Vivillon', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(667, 'Litleo', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(668, 'Pyroar', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(669, 'Flabebe', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(670, 'Floette', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(671, 'Florges', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(672, 'Skiddo', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(673, 'Gogoat', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(674, 'Pancham', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(675, 'Pangoro', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(676, 'Furfrou', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(677, 'Espurr', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(678, 'Meowstic', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(679, 'Honedge', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(680, 'Doublade', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(681, 'Aegislash', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(682, 'Spritzee', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(683, 'Aromatisse', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(684, 'Swirlix', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(685, 'Slurpuff', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(686, 'Inkay', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(687, 'Malamar', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(688, 'Binacle', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(689, 'Barbaracle', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(690, 'Skrelp', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(691, 'Dragalge', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(692, 'Clauncher', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(693, 'Clawitzer', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(694, 'Helioptile', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(695, 'Heliolisk', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(696, 'Tyrunt', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(697, 'Tyrantrum', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(698, 'Amaura', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(699, 'Aurorus', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(700, 'Sylveon', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(701, 'Hawlucha', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(702, 'Dedenne', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(703, 'Carbink', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(704, 'Goomy', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(705, 'Sliggoo', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(706, 'Goodra', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(707, 'Klefki', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(708, 'Phantump', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(709, 'Trevenant', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(710, 'Pumpkaboo', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(711, 'Gourgeist', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(712, 'Bergmite', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(713, 'Avalugg', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(714, 'Noibat', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(715, 'Noivern', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(716, 'Xerneas', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(717, 'Yveltal', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(718, 'Zygarde', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(719, 'Diancie', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(720, 'Hoopa', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(721, 'Volcanion', NULL, 0, 0, 0, 'Kalos', NULL, NULL, NULL, NULL, NULL, NULL),
(722, 'Rowlet', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(723, 'Dartrix', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(724, 'Decidueye', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(725, 'Litten', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(726, 'Torracat', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(727, 'Incineroar', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(728, 'Popplio', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(729, 'Brionne', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(730, 'Primarina', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(731, 'Pikipek', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(732, 'Trumbeak', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(733, 'Toucannon', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(734, 'Yungoos', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(735, 'Gumshoos', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(736, 'Grubbin', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(737, 'Charjabug', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(738, 'Vikavolt', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(739, 'Crabrawler', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(740, 'Crabominable', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(741, 'Oricorio', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(742, 'Cutiefly', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(743, 'Ribombee', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(744, 'Rockruff', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(745, 'Lycanroc', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(746, 'Wishiwashi', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(747, 'Mareanie', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(748, 'Toxapex', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(749, 'Mudbray', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(750, 'Mudsdale', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(751, 'Dewpider', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(752, 'Araquanid', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(753, 'Fomantis', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(754, 'Lurantis', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(755, 'Morelull', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(756, 'Shiinotic', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(757, 'Salandit', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(758, 'Salazzle', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(759, 'Stufful', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(760, 'Bewear', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(761, 'Bounsweet', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(762, 'Steenee', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(763, 'Tsareena', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(764, 'Comfey', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(765, 'Oranguru', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(766, 'Passimian', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(767, 'Wimpod', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(768, 'Golisopod', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(769, 'Sandygast', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(770, 'Palossand', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(771, 'Pyukumuku', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(772, 'Type: Null', 'Typhon', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(773, 'Silvally', 'Tartarus', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(774, 'Minior', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(775, 'Komala', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(776, 'Turtonator', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(777, 'Togedemaru', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(778, 'Mimikyu', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(779, 'Bruxish', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(780, 'Drampa', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(781, 'Dhelmise', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(782, 'Jangmo-o', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(783, 'Hakamo-o', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(784, 'Kommo-o', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(785, 'Tapu Koko', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(786, 'Tapu Lele', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(787, 'Tapu Bulu', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(788, 'Tapu Fini', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(789, 'Cosmog', 'Castor', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(790, 'Cosmoem', 'Pollux', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(791, 'Solgaleo', 'Helios', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(792, 'Lunala', 'Selene', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(793, 'Nihilego', 'Calypso', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(794, 'Buzzwole', 'Ares', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(795, 'Pheromosa', 'Aphrodite', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(796, 'Xurkitree', 'Zeus', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(797, 'Celesteela', 'Hephaestus', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(798, 'Kartana', 'Athena', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(799, 'Guzzlord', 'Bacchus', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(800, 'Necrozma', 'Chaos', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(801, 'Magearna', 'Hermes', 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL),
(802, 'Marshadow', NULL, 0, 0, 0, 'Alola', NULL, NULL, NULL, NULL, NULL, NULL);

-- --------------------------------------------------------

--
-- Table structure for table `Moves`
--
-- Creation: Jun 14, 2017 at 05:51 PM
--

CREATE TABLE `Moves` (
  `ID` int(5) NOT NULL,
  `Name` varchar(30) DEFAULT NULL,
  `Type` varchar(10) DEFAULT NULL,
  `Category` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- RELATIONSHIPS FOR TABLE `Moves`:
--

--
-- Dumping data for table `Moves`
--

INSERT INTO `Moves` (`ID`, `Name`, `Type`, `Category`) VALUES
(1, 'Pound', 'Normal', 'Physical'),
(2, 'Karate Chop', 'Fighting', 'Physical'),
(3, 'Double Slap', 'Normal', 'Physical'),
(4, 'Comet Punch', 'Normal', 'Physical'),
(5, 'Mega Punch', 'Normal', 'Physical'),
(6, 'Pay Day', 'Normal', 'Physical'),
(7, 'Fire Punch', 'Fire', 'Physical'),
(8, 'Ice Punch', 'Ice', 'Physical'),
(9, 'Thunder Punch', 'Electric', 'Physical'),
(10, 'Scratch', 'Normal', 'Physical'),
(11, 'Vice Grip', 'Normal', 'Physical'),
(12, 'Guillotine', 'Normal', 'Physical'),
(13, 'Razor Wind', 'Normal', 'Special'),
(14, 'Swords Dance', 'Normal', 'Status'),
(15, 'Cut', 'Normal', 'Physical'),
(16, 'Gust', 'Flying', 'Special'),
(17, 'Wing Attack', 'Flying', 'Physical'),
(18, 'Whirlwind', 'Normal', 'Status'),
(19, 'Fly', 'Flying', 'Physical'),
(20, 'Bind', 'Normal', 'Physical'),
(21, 'Slam', 'Normal', 'Physical'),
(22, 'Vine Whip', 'Grass', 'Physical'),
(23, 'Stomp', 'Normal', 'Physical'),
(24, 'Double Kick', 'Fighting', 'Physical'),
(25, 'Mega Kick', 'Normal', 'Physical'),
(26, 'Jump Kick', 'Fighting', 'Physical'),
(27, 'Rolling Kick', 'Fighting', 'Physical'),
(28, 'Sand Attack', 'Ground', 'Status'),
(29, 'Headbutt', 'Normal', 'Physical'),
(30, 'Horn Attack', 'Normal', 'Physical'),
(31, 'Fury Attack', 'Normal', 'Physical'),
(32, 'Horn Drill', 'Normal', 'Physical'),
(33, 'Tackle', 'Normal', 'Physical'),
(34, 'Body Slam', 'Normal', 'Physical'),
(35, 'Wrap', 'Normal', 'Physical'),
(36, 'Take Down', 'Normal', 'Physical'),
(37, 'Thrash', 'Normal', 'Physical'),
(38, 'Double-Edge', 'Normal', 'Physical'),
(39, 'Tail Whip', 'Normal', 'Status'),
(40, 'Poison Sting', 'Poison', 'Physical'),
(41, 'Twineedle', 'Bug', 'Physical'),
(42, 'Pin Missile', 'Bug', 'Physical'),
(43, 'Leer', 'Normal', 'Status'),
(44, 'Bite', 'Dark', 'Physical'),
(45, 'Growl', 'Normal', 'Status'),
(46, 'Roar', 'Normal', 'Status'),
(47, 'Sing', 'Normal', 'Status'),
(48, 'Supersonic', 'Normal', 'Status'),
(49, 'Sonic Boom', 'Normal', 'Special'),
(50, 'Disable', 'Normal', 'Status'),
(51, 'Acid', 'Poison', 'Special'),
(52, 'Ember', 'Fire', 'Special'),
(53, 'Flamethrower', 'Fire', 'Special'),
(54, 'Mist', 'Ice', 'Status'),
(55, 'Water Gun', 'Water', 'Special'),
(56, 'Hydro Pump', 'Water', 'Special'),
(57, 'Surf', 'Water', 'Special'),
(58, 'Ice Beam', 'Ice', 'Special'),
(59, 'Blizzard', 'Ice', 'Special'),
(60, 'Psybeam', 'Psychic', 'Special'),
(61, 'Bubble Beam', 'Water', 'Special'),
(62, 'Aurora Beam', 'Ice', 'Special'),
(63, 'Hyper Beam', 'Normal', 'Special'),
(64, 'Peck', 'Flying', 'Physical'),
(65, 'Drill Peck', 'Flying', 'Physical'),
(66, 'Submission', 'Fighting', 'Physical'),
(67, 'Low Kick', 'Fighting', 'Physical'),
(68, 'Counter', 'Fighting', 'Physical'),
(69, 'Seismic Toss', 'Fighting', 'Physical'),
(70, 'Strength', 'Normal', 'Physical'),
(71, 'Absorb', 'Grass', 'Special'),
(72, 'Mega Drain', 'Grass', 'Special'),
(73, 'Leech Seed', 'Grass', 'Status'),
(74, 'Growth', 'Normal', 'Status'),
(75, 'Razor Leaf', 'Grass', 'Physical'),
(76, 'Solar Beam', 'Grass', 'Special'),
(77, 'Poison Powder', 'Poison', 'Status'),
(78, 'Stun Spore', 'Grass', 'Status'),
(79, 'Sleep Powder', 'Grass', 'Status'),
(80, 'Petal Dance', 'Grass', 'Special'),
(81, 'String Shot', 'Bug', 'Status'),
(82, 'Dragon Rage', 'Dragon', 'Special'),
(83, 'Fire Spin', 'Fire', 'Special'),
(84, 'Thunder Shock', 'Electric', 'Special'),
(85, 'Thunderbolt', 'Electric', 'Special'),
(86, 'Thunder Wave', 'Electric', 'Status'),
(87, 'Thunder', 'Electric', 'Special'),
(88, 'Rock Throw', 'Rock', 'Physical'),
(89, 'Earthquake', 'Ground', 'Physical'),
(90, 'Fissure', 'Ground', 'Physical'),
(91, 'Dig', 'Ground', 'Physical'),
(92, 'Toxic', 'Poison', 'Status'),
(93, 'Confusion', 'Psychic', 'Special'),
(94, 'Psychic', 'Psychic', 'Special'),
(95, 'Hypnosis', 'Psychic', 'Status'),
(96, 'Meditate', 'Psychic', 'Status'),
(97, 'Agility', 'Psychic', 'Status'),
(98, 'Quick Attack', 'Normal', 'Physical'),
(99, 'Rage', 'Normal', 'Physical'),
(100, 'Teleport', 'Psychic', 'Status'),
(101, 'Night Shade', 'Ghost', 'Special'),
(102, 'Mimic', 'Normal', 'Status'),
(103, 'Screech', 'Normal', 'Status'),
(104, 'Double Team', 'Normal', 'Status'),
(105, 'Recover', 'Normal', 'Status'),
(106, 'Harden', 'Normal', 'Status'),
(107, 'Minimize', 'Normal', 'Status'),
(108, 'Smokescreen', 'Normal', 'Status'),
(109, 'Confuse Ray', 'Ghost', 'Status'),
(110, 'Withdraw', 'Water', 'Status'),
(111, 'Defense Curl', 'Normal', 'Status'),
(112, 'Barrier', 'Psychic', 'Status'),
(113, 'Light Screen', 'Psychic', 'Status'),
(114, 'Haze', 'Ice', 'Status'),
(115, 'Reflect', 'Psychic', 'Status'),
(116, 'Focus Energy', 'Normal', 'Status'),
(117, 'Bide', 'Normal', 'Physical'),
(118, 'Metronome', 'Normal', 'Status'),
(119, 'Mirror Move', 'Flying', 'Status'),
(120, 'Self-Destruct', 'Normal', 'Physical'),
(121, 'Egg Bomb', 'Normal', 'Physical'),
(122, 'Lick', 'Ghost', 'Physical'),
(123, 'Smog', 'Poison', 'Special'),
(124, 'Sludge', 'Poison', 'Special'),
(125, 'Bone Club', 'Ground', 'Physical'),
(126, 'Fire Blast', 'Fire', 'Special'),
(127, 'Waterfall', 'Water', 'Physical'),
(128, 'Clamp', 'Water', 'Physical'),
(129, 'Swift', 'Normal', 'Special'),
(130, 'Skull Bash', 'Normal', 'Physical'),
(131, 'Spike Cannon', 'Normal', 'Physical'),
(132, 'Constrict', 'Normal', 'Physical'),
(133, 'Amnesia', 'Psychic', 'Status'),
(134, 'Kinesis', 'Psychic', 'Status'),
(135, 'Soft-Boiled', 'Normal', 'Status'),
(136, 'High Jump Kick', 'Fighting', 'Physical'),
(137, 'Glare', 'Normal', 'Status'),
(138, 'Dream Eater', 'Psychic', 'Special'),
(139, 'Poison Gas', 'Poison', 'Status'),
(140, 'Barrage', 'Normal', 'Physical'),
(141, 'Leech Life', 'Bug', 'Physical'),
(142, 'Lovely Kiss', 'Normal', 'Status'),
(143, 'Sky Attack', 'Flying', 'Physical'),
(144, 'Transform', 'Normal', 'Status'),
(145, 'Bubble', 'Water', 'Special'),
(146, 'Dizzy Punch', 'Normal', 'Physical'),
(147, 'Spore', 'Grass', 'Status'),
(148, 'Flash', 'Normal', 'Status'),
(149, 'Psywave', 'Psychic', 'Special'),
(150, 'Splash', 'Normal', 'Status'),
(151, 'Acid Armor', 'Poison', 'Status'),
(152, 'Crabhammer', 'Water', 'Physical'),
(153, 'Explosion', 'Normal', 'Physical'),
(154, 'Fury Swipes', 'Normal', 'Physical'),
(155, 'Bonemerang', 'Ground', 'Physical'),
(156, 'Rest', 'Psychic', 'Status'),
(157, 'Rock Slide', 'Rock', 'Physical'),
(158, 'Hyper Fang', 'Normal', 'Physical'),
(159, 'Sharpen', 'Normal', 'Status'),
(160, 'Conversion', 'Normal', 'Status'),
(161, 'Tri Attack', 'Normal', 'Special'),
(162, 'Super Fang', 'Normal', 'Physical'),
(163, 'Slash', 'Normal', 'Physical'),
(164, 'Substitute', 'Normal', 'Status'),
(165, 'Struggle', 'Normal', 'Physical'),
(166, 'Sketch', 'Normal', 'Status'),
(167, 'Triple Kick', 'Fighting', 'Physical'),
(168, 'Thief', 'Dark', 'Physical'),
(169, 'Spider Web', 'Bug', 'Status'),
(170, 'Mind Reader', 'Normal', 'Status'),
(171, 'Nightmare', 'Ghost', 'Status'),
(172, 'Flame Wheel', 'Fire', 'Physical'),
(173, 'Snore', 'Normal', 'Special'),
(174, 'Curse', 'Ghost', 'Status'),
(175, 'Flail', 'Normal', 'Physical'),
(176, 'Conversion 2', 'Normal', 'Status'),
(177, 'Aeroblast', 'Flying', 'Special'),
(178, 'Cotton Spore', 'Grass', 'Status'),
(179, 'Reversal', 'Fighting', 'Physical'),
(180, 'Spite', 'Ghost', 'Status'),
(181, 'Powder Snow', 'Ice', 'Special'),
(182, 'Protect', 'Normal', 'Status'),
(183, 'Mach Punch', 'Fighting', 'Physical'),
(184, 'Scary Face', 'Normal', 'Status'),
(185, 'Feint Attack', 'Dark', 'Physical'),
(186, 'Sweet Kiss', 'Fairy', 'Status'),
(187, 'Belly Drum', 'Normal', 'Status'),
(188, 'Sludge Bomb', 'Poison', 'Special'),
(189, 'Mud-Slap', 'Ground', 'Special'),
(190, 'Octazooka', 'Water', 'Special'),
(191, 'Spikes', 'Ground', 'Status'),
(192, 'Zap Cannon', 'Electric', 'Special'),
(193, 'Foresight', 'Normal', 'Status'),
(194, 'Destiny Bond', 'Ghost', 'Status'),
(195, 'Perish Song', 'Normal', 'Status'),
(196, 'Icy Wind', 'Ice', 'Special'),
(197, 'Detect', 'Fighting', 'Status'),
(198, 'Bone Rush', 'Ground', 'Physical'),
(199, 'Lock-On', 'Normal', 'Status'),
(200, 'Outrage', 'Dragon', 'Physical'),
(201, 'Sandstorm', 'Rock', 'Status'),
(202, 'Giga Drain', 'Grass', 'Special'),
(203, 'Endure', 'Normal', 'Status'),
(204, 'Charm', 'Fairy', 'Status'),
(205, 'Rollout', 'Rock', 'Physical'),
(206, 'False Swipe', 'Normal', 'Physical'),
(207, 'Swagger', 'Normal', 'Status'),
(208, 'Milk Drink', 'Normal', 'Status'),
(209, 'Spark', 'Electric', 'Physical'),
(210, 'Fury Cutter', 'Bug', 'Physical'),
(211, 'Steel Wing', 'Steel', 'Physical'),
(212, 'Mean Look', 'Normal', 'Status'),
(213, 'Attract', 'Normal', 'Status'),
(214, 'Sleep Talk', 'Normal', 'Status'),
(215, 'Heal Bell', 'Normal', 'Status'),
(216, 'Return', 'Normal', 'Physical'),
(217, 'Present', 'Normal', 'Physical'),
(218, 'Frustration', 'Normal', 'Physical'),
(219, 'Safeguard', 'Normal', 'Status'),
(220, 'Pain Split', 'Normal', 'Status'),
(221, 'Sacred Fire', 'Fire', 'Physical'),
(222, 'Magnitude', 'Ground', 'Physical'),
(223, 'Dynamic Punch', 'Fighting', 'Physical'),
(224, 'Megahorn', 'Bug', 'Physical'),
(225, 'Dragon Breath', 'Dragon', 'Special'),
(226, 'Baton Pass', 'Normal', 'Status'),
(227, 'Encore', 'Normal', 'Status'),
(228, 'Pursuit', 'Dark', 'Physical'),
(229, 'Rapid Spin', 'Normal', 'Physical'),
(230, 'Sweet Scent', 'Normal', 'Status'),
(231, 'Iron Tail', 'Steel', 'Physical'),
(232, 'Metal Claw', 'Steel', 'Physical'),
(233, 'Vital Throw', 'Fighting', 'Physical'),
(234, 'Morning Sun', 'Normal', 'Status'),
(235, 'Synthesis', 'Grass', 'Status'),
(236, 'Moonlight', 'Fairy', 'Status'),
(237, 'Hidden Power', 'Normal', 'Special'),
(238, 'Cross Chop', 'Fighting', 'Physical'),
(239, 'Twister', 'Dragon', 'Special'),
(240, 'Rain Dance', 'Water', 'Status'),
(241, 'Sunny Day', 'Fire', 'Status'),
(242, 'Crunch', 'Dark', 'Physical'),
(243, 'Mirror Coat', 'Psychic', 'Special'),
(244, 'Psych Up', 'Normal', 'Status'),
(245, 'Extreme Speed', 'Normal', 'Physical'),
(246, 'Ancient Power', 'Rock', 'Special'),
(247, 'Shadow Ball', 'Ghost', 'Special'),
(248, 'Future Sight', 'Psychic', 'Special'),
(249, 'Rock Smash', 'Fighting', 'Physical'),
(250, 'Whirlpool', 'Water', 'Special'),
(251, 'Beat Up', 'Dark', 'Physical'),
(252, 'Fake Out', 'Normal', 'Physical'),
(253, 'Uproar', 'Normal', 'Special'),
(254, 'Stockpile', 'Normal', 'Status'),
(255, 'Spit Up', 'Normal', 'Special'),
(256, 'Swallow', 'Normal', 'Status'),
(257, 'Heat Wave', 'Fire', 'Special'),
(258, 'Hail', 'Ice', 'Status'),
(259, 'Torment', 'Dark', 'Status'),
(260, 'Flatter', 'Dark', 'Status'),
(261, 'Will-O-Wisp', 'Fire', 'Status'),
(262, 'Memento', 'Dark', 'Status'),
(263, 'Facade', 'Normal', 'Physical'),
(264, 'Focus Punch', 'Fighting', 'Physical'),
(265, 'Smelling Salts', 'Normal', 'Physical'),
(266, 'Follow Me', 'Normal', 'Status'),
(267, 'Nature Power', 'Normal', 'Status'),
(268, 'Charge', 'Electric', 'Status'),
(269, 'Taunt', 'Dark', 'Status'),
(270, 'Helping Hand', 'Normal', 'Status'),
(271, 'Trick', 'Psychic', 'Status'),
(272, 'Role Play', 'Psychic', 'Status'),
(273, 'Wish', 'Normal', 'Status'),
(274, 'Assist', 'Normal', 'Status'),
(275, 'Ingrain', 'Grass', 'Status'),
(276, 'Superpower', 'Fighting', 'Physical'),
(277, 'Magic Coat', 'Psychic', 'Status'),
(278, 'Recycle', 'Normal', 'Status'),
(279, 'Revenge', 'Fighting', 'Physical'),
(280, 'Brick Break', 'Fighting', 'Physical'),
(281, 'Yawn', 'Normal', 'Status'),
(282, 'Knock Off', 'Dark', 'Physical'),
(283, 'Endeavor', 'Normal', 'Physical'),
(284, 'Eruption', 'Fire', 'Special'),
(285, 'Skill Swap', 'Psychic', 'Status'),
(286, 'Imprison', 'Psychic', 'Status'),
(287, 'Refresh', 'Normal', 'Status'),
(288, 'Grudge', 'Ghost', 'Status'),
(289, 'Snatch', 'Dark', 'Status'),
(290, 'Secret Power', 'Normal', 'Physical'),
(291, 'Dive', 'Water', 'Physical'),
(292, 'Arm Thrust', 'Fighting', 'Physical'),
(293, 'Camouflage', 'Normal', 'Status'),
(294, 'Tail Glow', 'Bug', 'Status'),
(295, 'Luster Purge', 'Psychic', 'Special'),
(296, 'Mist Ball', 'Psychic', 'Special'),
(297, 'Feather Dance', 'Flying', 'Status'),
(298, 'Teeter Dance', 'Normal', 'Status'),
(299, 'Blaze Kick', 'Fire', 'Physical'),
(300, 'Mud Sport', 'Ground', 'Status'),
(301, 'Ice Ball', 'Ice', 'Physical'),
(302, 'Needle Arm', 'Grass', 'Physical'),
(303, 'Slack Off', 'Normal', 'Status'),
(304, 'Hyper Voice', 'Normal', 'Special'),
(305, 'Poison Fang', 'Poison', 'Physical'),
(306, 'Crush Claw', 'Normal', 'Physical'),
(307, 'Blast Burn', 'Fire', 'Special'),
(308, 'Hydro Cannon', 'Water', 'Special'),
(309, 'Meteor Mash', 'Steel', 'Physical'),
(310, 'Astonish', 'Ghost', 'Physical'),
(311, 'Weather Ball', 'Normal', 'Special'),
(312, 'Aromatherapy', 'Grass', 'Status'),
(313, 'Fake Tears', 'Dark', 'Status'),
(314, 'Air Cutter', 'Flying', 'Special'),
(315, 'Overheat', 'Fire', 'Special'),
(316, 'Odor Sleuth', 'Normal', 'Status'),
(317, 'Rock Tomb', 'Rock', 'Physical'),
(318, 'Silver Wind', 'Bug', 'Special'),
(319, 'Metal Sound', 'Steel', 'Status'),
(320, 'Grass Whistle', 'Grass', 'Status'),
(321, 'Tickle', 'Normal', 'Status'),
(322, 'Cosmic Power', 'Psychic', 'Status'),
(323, 'Water Spout', 'Water', 'Special'),
(324, 'Signal Beam', 'Bug', 'Special'),
(325, 'Shadow Punch', 'Ghost', 'Physical'),
(326, 'Extrasensory', 'Psychic', 'Special'),
(327, 'Sky Uppercut', 'Fighting', 'Physical'),
(328, 'Sand Tomb', 'Ground', 'Physical'),
(329, 'Sheer Cold', 'Ice', 'Special'),
(330, 'Muddy Water', 'Water', 'Special'),
(331, 'Bullet Seed', 'Grass', 'Physical'),
(332, 'Aerial Ace', 'Flying', 'Physical'),
(333, 'Icicle Spear', 'Ice', 'Physical'),
(334, 'Iron Defense', 'Steel', 'Status'),
(335, 'Block', 'Normal', 'Status'),
(336, 'Howl', 'Normal', 'Status'),
(337, 'Dragon Claw', 'Dragon', 'Physical'),
(338, 'Frenzy Plant', 'Grass', 'Special'),
(339, 'Bulk Up', 'Fighting', 'Status'),
(340, 'Bounce', 'Flying', 'Physical'),
(341, 'Mud Shot', 'Ground', 'Special'),
(342, 'Poison Tail', 'Poison', 'Physical'),
(343, 'Covet', 'Normal', 'Physical'),
(344, 'Volt Tackle', 'Electric', 'Physical'),
(345, 'Magical Leaf', 'Grass', 'Special'),
(346, 'Water Sport', 'Water', 'Status'),
(347, 'Calm Mind', 'Psychic', 'Status'),
(348, 'Leaf Blade', 'Grass', 'Physical'),
(349, 'Dragon Dance', 'Dragon', 'Status'),
(350, 'Rock Blast', 'Rock', 'Physical'),
(351, 'Shock Wave', 'Electric', 'Special'),
(352, 'Water Pulse', 'Water', 'Special'),
(353, 'Doom Desire', 'Steel', 'Special'),
(354, 'Psycho Boost', 'Psychic', 'Special'),
(355, 'Roost', 'Flying', 'Status'),
(356, 'Gravity', 'Psychic', 'Status'),
(357, 'Miracle Eye', 'Psychic', 'Status'),
(358, 'Wake-Up Slap', 'Fighting', 'Physical'),
(359, 'Hammer Arm', 'Fighting', 'Physical'),
(360, 'Gyro Ball', 'Steel', 'Physical'),
(361, 'Healing Wish', 'Psychic', 'Status'),
(362, 'Brine', 'Water', 'Special'),
(363, 'Natural Gift', 'Normal', 'Physical'),
(364, 'Feint', 'Normal', 'Physical'),
(365, 'Pluck', 'Flying', 'Physical'),
(366, 'Tailwind', 'Flying', 'Status'),
(367, 'Acupressure', 'Normal', 'Status'),
(368, 'Metal Burst', 'Steel', 'Physical'),
(369, 'U-turn', 'Bug', 'Physical'),
(370, 'Close Combat', 'Fighting', 'Physical'),
(371, 'Payback', 'Dark', 'Physical'),
(372, 'Assurance', 'Dark', 'Physical'),
(373, 'Embargo', 'Dark', 'Status'),
(374, 'Fling', 'Dark', 'Physical'),
(375, 'Psycho Shift', 'Psychic', 'Status'),
(376, 'Trump Card', 'Normal', 'Special'),
(377, 'Heal Block', 'Psychic', 'Status'),
(378, 'Wring Out', 'Normal', 'Special'),
(379, 'Power Trick', 'Psychic', 'Status'),
(380, 'Gastro Acid', 'Poison', 'Status'),
(381, 'Lucky Chant', 'Normal', 'Status'),
(382, 'Me First', 'Normal', 'Status'),
(383, 'Copycat', 'Normal', 'Status'),
(384, 'Power Swap', 'Psychic', 'Status'),
(385, 'Guard Swap', 'Psychic', 'Status'),
(386, 'Punishment', 'Dark', 'Physical'),
(387, 'Last Resort', 'Normal', 'Physical'),
(388, 'Worry Seed', 'Grass', 'Status'),
(389, 'Sucker Punch', 'Dark', 'Physical'),
(390, 'Toxic Spikes', 'Poison', 'Status'),
(391, 'Heart Swap', 'Psychic', 'Status'),
(392, 'Aqua Ring', 'Water', 'Status'),
(393, 'Magnet Rise', 'Electric', 'Status'),
(394, 'Flare Blitz', 'Fire', 'Physical'),
(395, 'Force Palm', 'Fighting', 'Physical'),
(396, 'Aura Sphere', 'Fighting', 'Special'),
(397, 'Rock Polish', 'Rock', 'Status'),
(398, 'Poison Jab', 'Poison', 'Physical'),
(399, 'Dark Pulse', 'Dark', 'Special'),
(400, 'Night Slash', 'Dark', 'Physical'),
(401, 'Aqua Tail', 'Water', 'Physical'),
(402, 'Seed Bomb', 'Grass', 'Physical'),
(403, 'Air Slash', 'Flying', 'Special'),
(404, 'X-Scissor', 'Bug', 'Physical'),
(405, 'Bug Buzz', 'Bug', 'Special'),
(406, 'Dragon Pulse', 'Dragon', 'Special'),
(407, 'Dragon Rush', 'Dragon', 'Physical'),
(408, 'Power Gem', 'Rock', 'Special'),
(409, 'Drain Punch', 'Fighting', 'Physical'),
(410, 'Vacuum Wave', 'Fighting', 'Special'),
(411, 'Focus Blast', 'Fighting', 'Special'),
(412, 'Energy Ball', 'Grass', 'Special'),
(413, 'Brave Bird', 'Flying', 'Physical'),
(414, 'Earth Power', 'Ground', 'Special'),
(415, 'Switcheroo', 'Dark', 'Status'),
(416, 'Giga Impact', 'Normal', 'Physical'),
(417, 'Nasty Plot', 'Dark', 'Status'),
(418, 'Bullet Punch', 'Steel', 'Physical'),
(419, 'Avalanche', 'Ice', 'Physical'),
(420, 'Ice Shard', 'Ice', 'Physical'),
(421, 'Shadow Claw', 'Ghost', 'Physical'),
(422, 'Thunder Fang', 'Electric', 'Physical'),
(423, 'Ice Fang', 'Ice', 'Physical'),
(424, 'Fire Fang', 'Fire', 'Physical'),
(425, 'Shadow Sneak', 'Ghost', 'Physical'),
(426, 'Mud Bomb', 'Ground', 'Special'),
(427, 'Psycho Cut', 'Psychic', 'Physical'),
(428, 'Zen Headbutt', 'Psychic', 'Physical'),
(429, 'Mirror Shot', 'Steel', 'Special'),
(430, 'Flash Cannon', 'Steel', 'Special'),
(431, 'Rock Climb', 'Normal', 'Physical'),
(432, 'Defog', 'Flying', 'Status'),
(433, 'Trick Room', 'Psychic', 'Status'),
(434, 'Draco Meteor', 'Dragon', 'Special'),
(435, 'Discharge', 'Electric', 'Special'),
(436, 'Lava Plume', 'Fire', 'Special'),
(437, 'Leaf Storm', 'Grass', 'Special'),
(438, 'Power Whip', 'Grass', 'Physical'),
(439, 'Rock Wrecker', 'Rock', 'Physical'),
(440, 'Cross Poison', 'Poison', 'Physical'),
(441, 'Gunk Shot', 'Poison', 'Physical'),
(442, 'Iron Head', 'Steel', 'Physical'),
(443, 'Magnet Bomb', 'Steel', 'Physical'),
(444, 'Stone Edge', 'Rock', 'Physical'),
(445, 'Captivate', 'Normal', 'Status'),
(446, 'Stealth Rock', 'Rock', 'Status'),
(447, 'Grass Knot', 'Grass', 'Special'),
(448, 'Chatter', 'Flying', 'Special'),
(449, 'Judgment', 'Normal', 'Special'),
(450, 'Bug Bite', 'Bug', 'Physical'),
(451, 'Charge Beam', 'Electric', 'Special'),
(452, 'Wood Hammer', 'Grass', 'Physical'),
(453, 'Aqua Jet', 'Water', 'Physical'),
(454, 'Attack Order', 'Bug', 'Physical'),
(455, 'Defend Order', 'Bug', 'Status'),
(456, 'Heal Order', 'Bug', 'Status'),
(457, 'Head Smash', 'Rock', 'Physical'),
(458, 'Double Hit', 'Normal', 'Physical'),
(459, 'Roar of Time', 'Dragon', 'Special'),
(460, 'Spacial Rend', 'Dragon', 'Special'),
(461, 'Lunar Dance', 'Psychic', 'Status'),
(462, 'Crush Grip', 'Normal', 'Physical'),
(463, 'Magma Storm', 'Fire', 'Special'),
(464, 'Dark Void', 'Dark', 'Status'),
(465, 'Seed Flare', 'Grass', 'Special'),
(466, 'Ominous Wind', 'Ghost', 'Special'),
(467, 'Shadow Force', 'Ghost', 'Physical'),
(468, 'Hone Claws', 'Dark', 'Status'),
(469, 'Wide Guard', 'Rock', 'Status'),
(470, 'Guard Split', 'Psychic', 'Status'),
(471, 'Power Split', 'Psychic', 'Status'),
(472, 'Wonder Room', 'Psychic', 'Status'),
(473, 'Psyshock', 'Psychic', 'Special'),
(474, 'Venoshock', 'Poison', 'Special'),
(475, 'Autotomize', 'Steel', 'Status'),
(476, 'Rage Powder', 'Bug', 'Status'),
(477, 'Telekinesis', 'Psychic', 'Status'),
(478, 'Magic Room', 'Psychic', 'Status'),
(479, 'Smack Down', 'Rock', 'Physical'),
(480, 'Storm Throw', 'Fighting', 'Physical'),
(481, 'Flame Burst', 'Fire', 'Special'),
(482, 'Sludge Wave', 'Poison', 'Special'),
(483, 'Quiver Dance', 'Bug', 'Status'),
(484, 'Heavy Slam', 'Steel', 'Physical'),
(485, 'Synchronoise', 'Psychic', 'Special'),
(486, 'Electro Ball', 'Electric', 'Special'),
(487, 'Soak', 'Water', 'Status'),
(488, 'Flame Charge', 'Fire', 'Physical'),
(489, 'Coil', 'Poison', 'Status'),
(490, 'Low Sweep', 'Fighting', 'Physical'),
(491, 'Acid Spray', 'Poison', 'Special'),
(492, 'Foul Play', 'Dark', 'Physical'),
(493, 'Simple Beam', 'Normal', 'Status'),
(494, 'Entrainment', 'Normal', 'Status'),
(495, 'After You', 'Normal', 'Status'),
(496, 'Round', 'Normal', 'Special'),
(497, 'Echoed Voice', 'Normal', 'Special'),
(498, 'Chip Away', 'Normal', 'Physical'),
(499, 'Clear Smog', 'Poison', 'Special'),
(500, 'Stored Power', 'Psychic', 'Special'),
(501, 'Quick Guard', 'Fighting', 'Status'),
(502, 'Ally Switch', 'Psychic', 'Status'),
(503, 'Scald', 'Water', 'Special'),
(504, 'Shell Smash', 'Normal', 'Status'),
(505, 'Heal Pulse', 'Psychic', 'Status'),
(506, 'Hex', 'Ghost', 'Special'),
(507, 'Sky Drop', 'Flying', 'Physical'),
(508, 'Shift Gear', 'Steel', 'Status'),
(509, 'Circle Throw', 'Fighting', 'Physical'),
(510, 'Incinerate', 'Fire', 'Special'),
(511, 'Quash', 'Dark', 'Status'),
(512, 'Acrobatics', 'Flying', 'Physical'),
(513, 'Reflect Type', 'Normal', 'Status'),
(514, 'Retaliate', 'Normal', 'Physical'),
(515, 'Final Gambit', 'Fighting', 'Special'),
(516, 'Bestow', 'Normal', 'Status'),
(517, 'Inferno', 'Fire', 'Special'),
(518, 'Water Pledge', 'Water', 'Special'),
(519, 'Fire Pledge', 'Fire', 'Special'),
(520, 'Grass Pledge', 'Grass', 'Special'),
(521, 'Volt Switch', 'Electric', 'Special'),
(522, 'Struggle Bug', 'Bug', 'Special'),
(523, 'Bulldoze', 'Ground', 'Physical'),
(524, 'Frost Breath', 'Ice', 'Special'),
(525, 'Dragon Tail', 'Dragon', 'Physical'),
(526, 'Work Up', 'Normal', 'Status'),
(527, 'Electroweb', 'Electric', 'Special'),
(528, 'Wild Charge', 'Electric', 'Physical'),
(529, 'Drill Run', 'Ground', 'Physical'),
(530, 'Dual Chop', 'Dragon', 'Physical'),
(531, 'Heart Stamp', 'Psychic', 'Physical'),
(532, 'Horn Leech', 'Grass', 'Physical'),
(533, 'Sacred Sword', 'Fighting', 'Physical'),
(534, 'Razor Shell', 'Water', 'Physical'),
(535, 'Heat Crash', 'Fire', 'Physical'),
(536, 'Leaf Tornado', 'Grass', 'Special'),
(537, 'Steamroller', 'Bug', 'Physical'),
(538, 'Cotton Guard', 'Grass', 'Status'),
(539, 'Night Daze', 'Dark', 'Special'),
(540, 'Psystrike', 'Psychic', 'Special'),
(541, 'Tail Slap', 'Normal', 'Physical'),
(542, 'Hurricane', 'Flying', 'Special'),
(543, 'Head Charge', 'Normal', 'Physical'),
(544, 'Gear Grind', 'Steel', 'Physical'),
(545, 'Searing Shot', 'Fire', 'Special'),
(546, 'Techno Blast', 'Normal', 'Special'),
(547, 'Relic Song', 'Normal', 'Special'),
(548, 'Secret Sword', 'Fighting', 'Special'),
(549, 'Glaciate', 'Ice', 'Special'),
(550, 'Bolt Strike', 'Electric', 'Physical'),
(551, 'Blue Flare', 'Fire', 'Special'),
(552, 'Fiery Dance', 'Fire', 'Special'),
(553, 'Freeze Shock', 'Ice', 'Physical'),
(554, 'Ice Burn', 'Ice', 'Special'),
(555, 'Snarl', 'Dark', 'Special'),
(556, 'Icicle Crash', 'Ice', 'Physical'),
(557, 'V-create', 'Fire', 'Physical'),
(558, 'Fusion Flare', 'Fire', 'Special'),
(559, 'Fusion Bolt', 'Electric', 'Physical'),
(560, 'Flying Press', 'Fighting', 'Physical'),
(561, 'Mat Block', 'Fighting', 'Status'),
(562, 'Belch', 'Poison', 'Special'),
(563, 'Rototiller', 'Ground', 'Status'),
(564, 'Sticky Web', 'Bug', 'Status'),
(565, 'Fell Stinger', 'Bug', 'Physical'),
(566, 'Phantom Force', 'Ghost', 'Physical'),
(567, 'Trick-or-Treat', 'Ghost', 'Status'),
(568, 'Noble Roar', 'Normal', 'Status'),
(569, 'Ion Deluge', 'Electric', 'Status'),
(570, 'Parabolic Charge', 'Electric', 'Special'),
(571, 'Forest\'s Curse', 'Grass', 'Status'),
(572, 'Petal Blizzard', 'Grass', 'Physical'),
(573, 'Freeze-Dry', 'Ice', 'Special'),
(574, 'Disarming Voice', 'Fairy', 'Special'),
(575, 'Parting Shot', 'Dark', 'Status'),
(576, 'Topsy-Turvy', 'Dark', 'Status'),
(577, 'Draining Kiss', 'Fairy', 'Special'),
(578, 'Crafty Shield', 'Fairy', 'Status'),
(579, 'Flower Shield', 'Fairy', 'Status'),
(580, 'Grassy Terrain', 'Grass', 'Status'),
(581, 'Misty Terrain', 'Fairy', 'Status'),
(582, 'Electrify', 'Electric', 'Status'),
(583, 'Play Rough', 'Fairy', 'Physical'),
(584, 'Fairy Wind', 'Fairy', 'Special'),
(585, 'Moonblast', 'Fairy', 'Special'),
(586, 'Boomburst', 'Normal', 'Special'),
(587, 'Fairy Lock', 'Fairy', 'Status'),
(588, 'King\'s Shield', 'Steel', 'Status'),
(589, 'Play Nice', 'Normal', 'Status'),
(590, 'Confide', 'Normal', 'Status'),
(591, 'Diamond Storm', 'Rock', 'Physical'),
(592, 'Steam Eruption', 'Water', 'Special'),
(593, 'Hyperspace Hole', 'Psychic', 'Special'),
(594, 'Water Shuriken', 'Water', 'Special'),
(595, 'Mystical Fire', 'Fire', 'Special'),
(596, 'Spiky Shield', 'Grass', 'Status'),
(597, 'Aromatic Mist', 'Fairy', 'Status'),
(598, 'Eerie Impulse', 'Electric', 'Status'),
(599, 'Venom Drench', 'Poison', 'Status'),
(600, 'Powder', 'Bug', 'Status'),
(601, 'Geomancy', 'Fairy', 'Status'),
(602, 'Magnetic Flux', 'Electric', 'Status'),
(603, 'Happy Hour', 'Normal', 'Status'),
(604, 'Electric Terrain', 'Electric', 'Status'),
(605, 'Dazzling Gleam', 'Fairy', 'Special'),
(606, 'Celebrate', 'Normal', 'Status'),
(607, 'Hold Hands', 'Normal', 'Status'),
(608, 'Baby-Doll Eyes', 'Fairy', 'Status'),
(609, 'Nuzzle', 'Electric', 'Physical'),
(610, 'Hold Back', 'Normal', 'Physical'),
(611, 'Infestation', 'Bug', 'Special'),
(612, 'Power-Up Punch', 'Fighting', 'Physical'),
(613, 'Oblivion Wing', 'Flying', 'Special'),
(614, 'Thousand Arrows', 'Ground', 'Physical'),
(615, 'Thousand Waves', 'Ground', 'Physical'),
(616, 'Land\'s Wrath', 'Ground', 'Physical'),
(617, 'Light of Ruin', 'Fairy', 'Special'),
(618, 'Origin Pulse', 'Water', 'Special'),
(619, 'Precipice Blades', 'Ground', 'Physical'),
(620, 'Dragon Ascent', 'Flying', 'Physical'),
(621, 'Hyperspace Fury', 'Dark', 'Physical'),
(622, 'Breakneck Blitz', 'Normal', 'Physical'),
(623, 'Breakneck Blitz', 'Normal', 'Special'),
(624, 'All-Out Pummeling', 'Fighting', 'Physical'),
(625, 'All-Out Pummeling', 'Fighting', 'Special'),
(626, 'Supersonic Skystrike', 'Flying', 'Physical'),
(627, 'Supersonic Skystrike', 'Flying', 'Special'),
(628, 'Acid Downpour', 'Poison', 'Physical'),
(629, 'Acid Downpour', 'Poison', 'Special'),
(630, 'Tectonic Rage', 'Ground', 'Physical'),
(631, 'Tectonic Rage', 'Ground', 'Special'),
(632, 'Continental Crush', 'Rock', 'Physical'),
(633, 'Continental Crush', 'Rock', 'Special'),
(634, 'Savage Spin-Out', 'Bug', 'Physical'),
(635, 'Savage Spin-Out', 'Bug', 'Special'),
(636, 'Never-Ending Nightmare', 'Ghost', 'Physical'),
(637, 'Never-Ending Nightmare', 'Ghost', 'Special'),
(638, 'Corkscrew Crash', 'Steel', 'Physical'),
(639, 'Corkscrew Crash', 'Steel', 'Special'),
(640, 'Inferno Overdrive', 'Fire', 'Physical'),
(641, 'Inferno Overdrive', 'Fire', 'Special'),
(642, 'Hydro Vortex', 'Water', 'Physical'),
(643, 'Hydro Vortex', 'Water', 'Special'),
(644, 'Bloom Doom', 'Grass', 'Physical'),
(645, 'Bloom Doom', 'Grass', 'Special'),
(646, 'Gigavolt Havoc', 'Electric', 'Physical'),
(647, 'Gigavolt Havoc', 'Electric', 'Special'),
(648, 'Shattered Psyche', 'Psychic', 'Physical'),
(649, 'Shattered Psyche', 'Psychic', 'Special'),
(650, 'Subzero Slammer', 'Ice', 'Physical'),
(651, 'Subzero Slammer', 'Ice', 'Special'),
(652, 'Devastating Drake', 'Dragon', 'Physical'),
(653, 'Devastating Drake', 'Dragon', 'Special'),
(654, 'Black Hole Eclipse', 'Dark', 'Physical'),
(655, 'Black Hole Eclipse', 'Dark', 'Special'),
(656, 'Twinkle Tackle', 'Fairy', 'Physical'),
(657, 'Twinkle Tackle', 'Fairy', 'Special'),
(658, 'Catastropika', 'Electric', 'Physical'),
(659, 'Shore Up', 'Ground', 'Status'),
(660, 'First Impression', 'Bug', 'Physical'),
(661, 'Baneful Bunker', 'Poison', 'Status'),
(662, 'Spirit Shackle', 'Ghost', 'Physical'),
(663, 'Darkest Lariat', 'Dark', 'Physical'),
(664, 'Sparkling Aria', 'Water', 'Special'),
(665, 'Ice Hammer', 'Ice', 'Physical'),
(666, 'Floral Healing', 'Fairy', 'Status'),
(667, 'High Horsepower', 'Ground', 'Physical'),
(668, 'Strength Sap', 'Grass', 'Status'),
(669, 'Solar Blade', 'Grass', 'Physical'),
(670, 'Leafage', 'Grass', 'Physical'),
(671, 'Spotlight', 'Normal', 'Status'),
(672, 'Toxic Thread', 'Poison', 'Status'),
(673, 'Laser Focus', 'Normal', 'Status'),
(674, 'Gear Up', 'Steel', 'Status'),
(675, 'Throat Chop', 'Dark', 'Physical'),
(676, 'Pollen Puff', 'Bug', 'Special'),
(677, 'Anchor Shot', 'Steel', 'Physical'),
(678, 'Psychic Terrain', 'Psychic', 'Status'),
(679, 'Lunge', 'Bug', 'Physical'),
(680, 'Fire Lash', 'Fire', 'Physical'),
(681, 'Power Trip', 'Dark', 'Physical'),
(682, 'Burn Up', 'Fire', 'Special'),
(683, 'Speed Swap', 'Psychic', 'Status'),
(684, 'Smart Strike', 'Steel', 'Physical'),
(685, 'Purify', 'Poison', 'Status'),
(686, 'Revelation Dance', 'Normal', 'Special'),
(687, 'Core Enforcer', 'Dragon', 'Special'),
(688, 'Trop Kick', 'Grass', 'Physical'),
(689, 'Instruct', 'Psychic', 'Status'),
(690, 'Beak Blast', 'Flying', 'Physical'),
(691, 'Clanging Scales', 'Dragon', 'Special'),
(692, 'Dragon Hammer', 'Dragon', 'Physical'),
(693, 'Brutal Swing', 'Dark', 'Physical'),
(694, 'Aurora Veil', 'Ice', 'Status'),
(695, 'Sinister Arrow Raid', 'Ghost', 'Physical'),
(696, 'Malicious Moonsault', 'Dark', 'Physical'),
(697, 'Oceanic Operetta', 'Water', 'Special'),
(698, 'Guardian of Alola', 'Fairy', 'Special'),
(699, 'Soul-Stealing 7-Star Strike', 'Ghost', 'Physical'),
(700, 'Stoked Sparksurfer', 'Electric', 'Special'),
(701, 'Pulverizing Pancake', 'Normal', 'Physical'),
(702, 'Extreme Evoboost', 'Normal', 'Status'),
(703, 'Genesis Supernova', 'Psychic', 'Special'),
(704, 'Shell Trap', 'Fire', 'Special'),
(705, 'Fleur Cannon', 'Fairy', 'Special'),
(706, 'Psychic Fangs', 'Psychic', 'Physical'),
(707, 'Stomping Tantrum', 'Ground', 'Physical'),
(708, 'Shadow Bone', 'Ghost', 'Physical'),
(709, 'Accelerock', 'Rock', 'Physical'),
(710, 'Liquidation', 'Water', 'Physical'),
(711, 'Prismatic Laser', 'Psychic', 'Special'),
(712, 'Spectral Thief', 'Ghost', 'Physical'),
(713, 'Sunsteel Strike', 'Steel', 'Physical'),
(714, 'Moongeist Beam', 'Ghost', 'Special'),
(715, 'Tearful Look', 'Normal', 'Status'),
(716, 'Zing Zap', 'Electric', 'Physical'),
(717, 'Nature\'s Madness', 'Fairy', 'Special'),
(718, 'Multi-Attack', 'Normal', 'Physical'),
(719, '10,000,000 Volt Thunderbolt', 'Electric', 'Special');

-- --------------------------------------------------------

--
-- Table structure for table `Natures`
--
-- Creation: Jun 14, 2017 at 05:50 PM
--

CREATE TABLE `Natures` (
  `ID` int(2) NOT NULL,
  `Name` varchar(7) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- RELATIONSHIPS FOR TABLE `Natures`:
--

--
-- Dumping data for table `Natures`
--

INSERT INTO `Natures` (`ID`, `Name`) VALUES
(1, 'Adamant'),
(2, 'Bashful'),
(3, 'Bold'),
(4, 'Brave'),
(5, 'Calm'),
(6, 'Careful'),
(7, 'Docile'),
(8, 'Gentle'),
(9, 'Hardy'),
(10, 'Hasty'),
(11, 'Impish'),
(12, 'Jolly'),
(13, 'Lax'),
(14, 'Lonely'),
(15, 'Mild'),
(16, 'Modest'),
(17, 'Naive'),
(18, 'Naughty'),
(19, 'Quiet'),
(20, 'Quirky'),
(21, 'Rash'),
(22, 'Relaxed'),
(23, 'Sassy'),
(24, 'Serious'),
(25, 'Timid');

-- --------------------------------------------------------

--
-- Table structure for table `Regions`
--
-- Creation: Jun 14, 2017 at 05:46 PM
--

CREATE TABLE `Regions` (
  `ID` int(2) NOT NULL,
  `Name` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- RELATIONSHIPS FOR TABLE `Regions`:
--

--
-- Dumping data for table `Regions`
--

INSERT INTO `Regions` (`ID`, `Name`) VALUES
(7, 'Alola'),
(3, 'Hoenn'),
(2, 'Johto'),
(6, 'Kalos'),
(1, 'Kanto'),
(4, 'Sinnoh'),
(5, 'Unova');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Learnsets`
--
ALTER TABLE `Learnsets`
  ADD UNIQUE KEY `Move` (`Species`,`Move`,`Gen`);

--
-- Indexes for table `Masterlist`
--
ALTER TABLE `Masterlist`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Species` (`ID`,`Species`) USING BTREE,
  ADD UNIQUE KEY `Nickname` (`Nickname`);

--
-- Indexes for table `Moves`
--
ALTER TABLE `Moves`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Name` (`ID`,`Name`);

--
-- Indexes for table `Natures`
--
ALTER TABLE `Natures`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Name` (`Name`);

--
-- Indexes for table `Regions`
--
ALTER TABLE `Regions`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Name` (`Name`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Masterlist`
--
ALTER TABLE `Masterlist`
  MODIFY `ID` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=803;

--
-- AUTO_INCREMENT for table `Moves`
--
ALTER TABLE `Moves`
  MODIFY `ID` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=720;

--
-- AUTO_INCREMENT for table `Natures`
--
ALTER TABLE `Natures`
  MODIFY `ID` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT for table `Regions`
--
ALTER TABLE `Regions`
  MODIFY `ID` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
